version: '3.7'

services:
  registry:
    image: registry:2
    ports:
      - 5000:5000
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - ./auth:/auth
      - ./data:/data
  nginx:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    image: registry/nginx
    container_name: registry_nginx
    environment:
      - DOMAIN=${DOMAIN}
      - EMAIL=contacto@placeholder.cl
    network_mode: "host"
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/